### ISSUE TITLE
OAC

### ISSUE THREAD

**Issue by LegitSoulja** [LegitSoulja/OAC#1]
@Andrews54757 @SharkFinPro

This is the non-encrypted safe oa client development repo, until almost finished release, in which the crypto, and other will be added later......

@Andrews54757 I will need some help with a few things, basically knowing what is what, and if this or that can be removed, or replaced or done in a different way. I haven't got down to the packets/connections yet, so bare with me.

I am trying to make this code clean/organized/simple and small in size.

Make sure that you stay up to date with code, and submit PR's only!. Thanks

**Comment by LegitSoulja** [comment]
Please don't star, watch, nor fork this project. Thanks.

**Comment by LegitSoulja** [comment]
@Andrews54757 it'll be nice for a recursive obfuscation that'll output the files into a specific directory. Just a thought. It'll come in handy, for this especially, unless I do things differently and not use requireJS

**Comment by Andrews54757** [comment]
@LegitSoulja So is the client code public indefinitely?

**Comment by LegitSoulja** [comment]
@Andrews54757 no

**Comment by LegitSoulja** [comment]
@Andrews54757 

I would make it private, however it's not worth it the budge, BUT

it's here for all of us to work on since I can't work on this 24/7.

We won't fully finish it here w/ network aspects. Once the basics are finished this will be deleted.

Hmm, we could however make a base for Ogar, but it'll have to be paid for, depends on how our client turns out.

**Comment by Andrews54757** [comment]
@LegitSoulja This is not private at all. People have already discovered it

**Comment by LegitSoulja** [comment]
@Andrews54757 I doubt it, but I'm closing these issues just in-case. You know how keywords and search engines work nowadays.

**Comment by LegitSoulja** [comment]
@Andrews54757, @SharkFinPro

Discussion in PRs.
